{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stzteam.features.unitprocessor",
    "module": "UnitProcessor",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UnitProcessor-1.0.0.jar",
          "url": "UnitProcessor-1.0.0.jar",
          "size": 5017,
          "sha512": "7e763c877f1ab4b60e3996b418178ab1c5bffedf84fdf547979bd2af5d9a863b568766c0c52a559267c3d5bf59cb24003b67719a572addcb3e8ee5f23d692abd",
          "sha256": "d075a382a7767d5f5eec54b0cd047485f5402cfef6a450b8501fa7495d740ec2",
          "sha1": "e212d80decc4b2cd98b58ae3896b7017229bf975",
          "md5": "be01491c3febc8681f0639d0f16d4bf2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "com.stzteam.forgemini",
          "module": "ForgeMini",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.stzteam.mars",
          "module": "Mars",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "UnitProcessor-1.0.0.jar",
          "url": "UnitProcessor-1.0.0.jar",
          "size": 5017,
          "sha512": "7e763c877f1ab4b60e3996b418178ab1c5bffedf84fdf547979bd2af5d9a863b568766c0c52a559267c3d5bf59cb24003b67719a572addcb3e8ee5f23d692abd",
          "sha256": "d075a382a7767d5f5eec54b0cd047485f5402cfef6a450b8501fa7495d740ec2",
          "sha1": "e212d80decc4b2cd98b58ae3896b7017229bf975",
          "md5": "be01491c3febc8681f0639d0f16d4bf2"
        }
      ]
    }
  ]
}
